### PR TITLE
fix latex rendering

### PR DESCRIPTION
**Pull request by agramfort**
pdf manual looks like this now

[OpenMEEG.pdf](https://github.com/openmeeg/openmeeg.github.io/files/1277211/OpenMEEG.pdf)

cc @mclerc @papadop

### CODE REVIEW

**Comment by mclerc** [comment]
Merci Alex 
Je vais regarder de près la différence - 
déjà à première vue on a perdu quelques couleurs en route. 

Maureen 

----- Mail original -----

| pdf manual looks like this now

| OpenMEEG.pdf

| cc @mclerc @papadop

| You can view, comment on, or merge this pull request online at:

| https://github.com/openmeeg/openmeeg.github.io/pull/6
| Commit Summary

| * fix latex rendering
| File Changes

| * M conf.py (8)
| * D documentation.php (44)
| * D download.php (72)
| * M tutorial.rst (71)
| Patch Links:

| * https://github.com/openmeeg/openmeeg.github.io/pull/6.patch
| * https://github.com/openmeeg/openmeeg.github.io/pull/6.diff

| —
| You are receiving this because you were mentioned.
| Reply to this email directly, view it on GitHub , or mute the thread .

**Comment by agramfort** [comment]
I'll see how to fix the colors. I accept the challenge :)

to make the pdf attached

git checkout source
make latex
cd build/latex
pdflatex OpenMEEG_manual.tex

**Comment by agramfort** [comment]
[OpenMEEG_manual.pdf](https://github.com/openmeeg/openmeeg.github.io/files/1280020/OpenMEEG_manual.pdf)

here is how it looks like now with the colors.

can I merge?

**Comment by mclerc** [comment]
Thanks this looks good. 
It's handy to have a printable consolidated view of the web pages (for me easier to see all that's to be updated than on screen). 

What's the workflow for generating the pdf ? 
Does it require any hand-tweaking ? 

Maureen 

----- Mail original -----

| OpenMEEG_manual.pdf

| here is how it looks like now with the colors.

| can I merge?

| —
| You are receiving this because you were mentioned.
| Reply to this email directly, view it on GitHub , or mute the thread .

**Comment by agramfort** [comment]
git clone git@github.com:openmeeg/openmeeg.github.io.git
cd openmeeg.github.io
git checkout source
make html  # generates web page in build/html
make latex  # generates tex files in build/latex
cd build/latex
pdflatex OpenMEEG_manual.tex

let me know if you need help

**Comment by mclerc** [comment]
_Trying to_ 
> make html
_runs into trouble:_
Running Sphinx v1.2.3

Extension error:
Could not import extension sphinx.ext.imgmath (exception: No module named imgmath)
Makefile:33: recipe for target 'html' failed

**Comment by agramfort** [comment]
what version are you using?

for me:

$ sphinx-build --version
Sphinx (sphinx-build) 1.5.6

**Comment by mclerc** [comment]
1.2.3 
Shipped with fc23
Maureen

**Comment by agramfort** [comment]
any chance you can update?

https://apps.fedoraproject.org/packages/python-sphinx

**Pull request merged**
