### PR TITLE
getting started with tutorial migration

### PR DESCRIPTION
**Pull request by agramfort**
cc @eolivi 

here is demo with the smallest file to convert Data.tex

### CODE REVIEW

**Comment by agramfort** [comment]
ok done a full first pass merging.

**Comment by agramfort** [comment]
see http://openmeeg.github.io/tutorial.html

@eolivi can you take over? This needs a serious clean up. There is
a lot of information duplication and errors :(

then we can remove all the latex from the main source tree.

**Comment by eolivi** [comment]
ok I continue

**Comment by eolivi** [comment]
a few questions please:
- where do I start ?
- did you fully finish tutorial.rst ?
- why files are named tutorial.rst.txt why txt ?
- how can I see the output ? I use to do the vizualization with ;restview' ? with sphinx (http://www.sphinx-doc.org/en/stable/) I'm having a look ?
- what are the other files important ? in OM/doc we had: Appendix, Commands, Context, Data, tutorial, but we only compiled tutorial (I think)
- I check all that files ? contact.rst.txt  index.rst.txt  license.rst.txt  publications.rst.txt  tutorial.rst.txt  why_openmeeg.rst.txt

I'm asking so that we don't do redundant work (I had already started the conversion of tutorial.tex-> rst)

**Comment by eolivi** [comment]
Je suis en train de voir sphinx.
il faut un config.py, je ne sais pas si t'as oublié de le commité, pour ensuite pouvoir faire un 
`sphinx-build -b html _sources build` 
 n'est-ce pas ?

**Comment by eolivi** [comment]
ok,,... en fait j'avais un repo completement different.. avec les fichiers html, etc... maintenant je suis capable de compiler

**Comment by agramfort** [comment]
yes you should build from the branch "source"

I just run:

make html

in the folder

**Comment by eolivi** [comment]
thx got it now, but I was on master before ....

**Pull request merged**
